SELECT SUM(PTS_home), NICKNAME, TEAM_ID, ABBREVIATION FROM GAMES INNER JOIN TEAMS 
ON games.HOME_TEAM_ID = teams.TEAM_ID
WHERE SEASON IN (2012, 2019)
GROUP BY TEAM_ID ORDER BY SUM(PTS_home) DESC LIMIT 5;


